In [1]:
import numpy as np
import pydicom as dicom

In [16]:
data = np.array([[[1,2],[2,2],[4,1]], [[5,6],[3,3],[2,1]]])
print(data.shape)
std = np.std(data)
print(type(std))
print(std)
print(np.float32(std))


data = np.array([[1,2,5],[2,6,9]])
std = np.std(data)
std

(2, 3, 2)
<class 'numpy.float64'>
1.5456030825826172
1.545603


2.7938424357067015

In [43]:
# Calculate the mean and std of the dicom images in training set
    
file_path = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22580341_5eae9beae14d26fd_MG_R_CC_ANON.dcm'
data = dicom.dcmread(file_path).pixel_array
std = np.std(data)
print(std)
normalised_std = np.float32(std) / np.int(65535)
print(normalised_std)
print(type(normalised_std))
print(np.float32(normalised_std))

mean = np.mean(data)
print(mean)
normalised_mean = np.float32(mean) /np.int(65535)
print(normalised_mean)
print(type(normalised_mean))
print(np.float32(normalised_mean))

data = np.array([[2,3,4],[5,2,1]])
mean = np.mean(data)
mean

print("*******************")
data = np.array([[2,3,4],[5,5,5]])
test =data.flatten()
print(test)
print(np.std(test))
std = np.std(data)
std

598.390969636191
0.00913086123767357
<class 'numpy.float64'>
0.009130862
325.4349908682016
0.0049658197536979285
<class 'numpy.float64'>
0.00496582
*******************
[2 3 4 5 5 5]
1.1547005383792515


1.1547005383792515

In [1]:
import numpy as np
import pydicom as dicom


In [12]:
file_path_1 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\20587810_81cd83d2f4d78528_MG_L_ML_ANON.dcm'
file_path_2 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\30011674_6968748e66837bc7_MG_L_CC_ANON.dcm'
file_path_3 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22678694_61b13c59bcba149e_MG_L_ML_ANON.dcm'
file_path_4 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\50996352_6aba0b402889a16f_MG_R_ML_ANON.dcm'
file_path_5 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22614379_d065adcb9905b973_MG_L_CC_ANON.dcm'
file_path_6 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22580244_5530d5782fc89dd7_MG_R_ML_ANON.dcm'
file_path_7 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22580341_5eae9beae14d26fd_MG_R_CC_ANON.dcm'
file_path_8 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22427840_bbd6a3a35438c11b_MG_R_CC_ANON.dcm'
file_path_9 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\20587054_b6a4f750c6df4f90_MG_R_CC_ANON.dcm'
file_path_10 = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\53582764_465aa5ec1b59efc6_MG_R_ML_ANON.dcm'

file_path_array = []
for x in range(10):
    file_path_temp = 'file_path_{}'.format(x+1)
    file_path_array.append(eval(file_path_temp))
print(file_path_array)

dicom_image_array = np.uint16(np.zeros([3328,2560,10]))
print(type(dicom_image_array[2,2]))
for i in range(10):
    file_path_temp_new = file_path_array[i]
    dicom_image_array[:,:,i] = dicom.dcmread(file_path_temp_new).pixel_array
print("mean is: ", np.mean(dicom_image_array))
print("std is: ", np.std(dicom_image_array))
print("normalised mean is: ", np.float32(np.mean(dicom_image_array) / 65535))
print("normalise std is: ", np.float32(np.std(dicom_image_array) / 65535 ))

['D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\20587810_81cd83d2f4d78528_MG_L_ML_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\30011674_6968748e66837bc7_MG_L_CC_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\22678694_61b13c59bcba149e_MG_L_ML_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\50996352_6aba0b402889a16f_MG_R_ML_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\22614379_d065adcb9905b973_MG_L_CC_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\22580244_5530d5782fc89dd7_MG_R_ML_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\22580341_5eae9beae14d26fd_MG_R_CC_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\22427840_bbd6a3a35438c11b_MG_R_CC_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\all_DICOM_files\\AllDICOMs\\20587054_b6a4f750c6df4f90_MG_R_CC_ANON.dcm', 'D:\\Studying\\RetinaNet_Project\\al

In [3]:
file_path = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\20587810_81cd83d2f4d78528_MG_L_ML_ANON.dcm'
data = dicom.dcmread(file_path).pixel_array
x = data.astype(np.float32)
x = x / 65535.0
x = (x - 0.008) / 0.011
print(type(x[2,2]))
print(x[2,2])

x_repo = read_image_bgr(file_path)
x_final = preprocess_image(x_repo, mode='caffe')
print(type(x_final[2,2,2]))
print(x_final[2,2,0])
print(x == x_final[:,:,2])

<class 'numpy.float32'>
1.7197196
<class 'numpy.float32'>
1.7197196
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [22]:
import numpy as np
import pydicom as dicom
import pandas as pd

final_pixel_array = []

file_path = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22613822_45c7f44839fd9e68_MG_R_ML_ANON.dcm'
dicom_array = dicom.dcmread(file_path).pixel_array
print(dicom_array.shape)
temp_shape = dicom_array.shape
counter = 0
for i in range(temp_shape[0]):
    for j in range(temp_shape[1]):
        temp = dicom_array[i, j]
        counter = counter + 1
print(counter)

(4084, 3328)
4083


In [4]:
import numpy as np
import pydicom as dicom
import pandas as pd

excel_file_path = r'D:\Studying\RetinaNet_Project_csv\new_version\on_my_own_pc\75train_25val_16test\for_calculate_mean_and_std\training_annotations.xlsx'
data_frame = pd.read_excel(excel_file_path)
image_path_dataframe = data_frame['image_path']
print(image_path_dataframe)
# List for storing all image path
image_path_list = np.array(image_path_dataframe).tolist()
# Storing all the non-zero pixels
final_pixel_array = []

for image_index in range (75):
    image_path_temp = image_path_list[image_index]
    dicom_array_temp = dicom.dcmread(image_path_temp).pixel_array
    print(dicom_array_temp.shape)
    image_shape_temp = dicom_array_temp.shape
    for i in range(image_shape_temp[0]):
        for j in range(image_shape_temp[1]):
            temp_pixel_value = dicom_array_temp[i, j]
            if(temp_pixel_value!=0):
                final_pixel_array.append(temp_pixel_value)

final_pixel_array_np = np.array(final_pixel_array)
dicom_mean = np.mean(final_pixel_array_np)
dicom_std = np.std(final_pixel_array_np)
print("Mean is: ", dicom_mean)
print("Std is: ", dicom_std)

0      D:\Studying\RetinaNet_Project\all_DICOM_files\...
1      D:\Studying\RetinaNet_Project\all_DICOM_files\...
2      D:\Studying\RetinaNet_Project\all_DICOM_files\...
3      D:\Studying\RetinaNet_Project\all_DICOM_files\...
4      D:\Studying\RetinaNet_Project\all_DICOM_files\...
                             ...                        
257    D:\Studying\RetinaNet_Project\all_DICOM_files\...
258    D:\Studying\RetinaNet_Project\all_DICOM_files\...
259    D:\Studying\RetinaNet_Project\all_DICOM_files\...
260    D:\Studying\RetinaNet_Project\all_DICOM_files\...
261    D:\Studying\RetinaNet_Project\all_DICOM_files\...
Name: image_path, Length: 262, dtype: object
(3328, 2560)
(3328, 2560)
(3328, 2560)
(4084, 3328)
(3328, 2560)
(4084, 3328)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(4084, 3328)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(4084, 3328)
(3328, 2560)
(4084, 3328)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(3328, 2560)
(4084, 3328)
(33

In [4]:
import numpy as np
x = np.uint8(123)
print(type(x))
x = x.astype(np.float32)
x = x / 133.5
print(type(x))


<class 'numpy.uint8'>
<class 'numpy.float64'>


In [6]:
from keras_retinanet.utils.image import read_image_bgr

file_path = r'D:\Studying\RetinaNet_Project\all_DICOM_files\AllDICOMs\22613822_45c7f44839fd9e68_MG_R_ML_ANON.dcm'
test = read_image_bgr(file_path)
print(test)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
